name: Invoke Supabase Edge Function Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Send restock notifications
        run: |
          curl -i --location --request POST '${{ secrets.SUPABASE_FUNCTION_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}'
